/products:
  get:
    tags:
      - Products
    summary: Get all products
    responses:
      "200":
        description: List of products
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Product"

/products/create:
  post:
    tags:
      - Products
    summary: Create a new product
    security:
      - cookieAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductCreateInput"
    responses:
      "201":
        description: Product created successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"


/products/category/create:
  post:
    tags:
      - Products
    summary: Create a new category
    security:
      - cookieAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CategoryCreateInput"
    responses:
      "201":
        description: Category created successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"

/products/category:
  get:
    tags:
      - Products
    summary: Get all categories
    responses:
      "200":
        description: List of categories
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Category"
                
